blog/urls.py
from django.urls import path
from .views import homeview, detailview, commentview, aboutmeview,postcreateview, AllPostsView, draftview, reviewview

app_name = "blog"
#url patterns for the blog application
urlpatterns = [
	path("",homeview,name="blog_home"),
	path("detail/<int:post_id>/",detailview,name="post_detail"),
	path("detail/<int:post_id>/comment/>", commentview, name="comment"),
	path("elijah/",aboutmeview,name="aboutme"),
	path("post_create",postcreateview,name="create"),
	path("all/",AllPostsView.as_view(),name="all"),
	path("draft/<int:post_id>/",draftview,name="draft"),
	path("review/",reviewview,name="review")
]

myblog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('',include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image

# Create your models here.
class Post(models.Model):
    title = models.TextField()
    subtitle = models.TextField()
    image = models.TextField()
    content = models.TextField()
    publish = models.BooleanField(default=False)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

    #     img = Image.open(self.image.path)

    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

    def __str__(self):
    	return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


#comment model
class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    safe = models.BooleanField(default=False)

    def __str__(self):
        return self.author.username



#contacts	
class Contact(models.Model):
    email = models.CharField(max_length=100)
    message = models.TextField()
    subject = models.CharField(max_length=200)

    def __str__(self):
        return self.subject

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Post,Comment, Contact
# Create your views here.

def homeview(request):
    posts = Post.objects.filter(publish=True).order_by('-date_posted')[:5]
    return render(request,'blog/home.html',{"posts":posts})



class AllPostsView(generic.ListView):
    template_name = 'blog/all.html'
    ordering = ['-date_posted']
    model = Post
    context_object_name = 'posts'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(publish=True)
        return context


def detailview(request,post_id):
    post = get_object_or_404(Post,pk=post_id)

    if post.publish:
        comments = post.comment_set.all().order_by("-date_posted")

        context = {
            "post":post,
            "comments":comments
        }
        return render(request,'blog/detail.html',context)
    else :
        return HttpResponseRedirect(reverse('blog:review'))

def commentview(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    content = request.POST["comment"]
    author = request.user
    the_comment = Comment.objects.create(
        content=content,
        post=post,
        author=author
        )
    the_comment.save()
    return HttpResponseRedirect(reverse('blog:post_detail', args=([post.id])))

def aboutmeview(request):
    if request.method == "POST":
        message = request.POST['message']
        email = request.POST['email']
        subject = request.POST['subject']

        send_mail(
            subject,
            message+"\n Sender's email: "+email,
            'elijahokellp@gmail.com',
            ['elijahokello90@gmail.com'],
            fail_silently=False,
            )
        contact = Contact.objects.create(email=email,message=message,subject=subject)
        contact.save()
        messages.success(request, f'Your message has been received successfully')
        return HttpResponseRedirect(reverse('blog:aboutme'))
    else:
        return render(request,'blog/about_me.html')

@login_required
def postcreateview(request):
    if request.method == "POST":
        post_content = request.POST['content'];
        post_title = request.POST['title']
        post_subtitle = request.POST['subtitle']
        image = request.POST['image']
        post_author = request.user

        if post_author.is_superuser:
            publish = True
            post = Post.objects.create(title=post_title,subtitle=post_subtitle,content=post_content,publish=publish,author=post_author,image=image)
            post.save()
            return HttpResponseRedirect(reverse('blog:draft',args=([post.id])))
        else:
            post = Post.objects.create(title=post_title,subtitle=post_subtitle,content=post_content,author=post_author,image=image)
            post.save()
            send_mail(
                'Post Has Been Created',
                'Please review the blog post',
                'elijahokellp@gmail.com',
                ['elijahokello90@gmail.com'],
                fail_silently=False,
                )
            return HttpResponseRedirect(reverse('blog:draft',args=([post.id])))
    else:
        return render(request,"blog/create.html")    


def draftview(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    comments = post.comment_set.all().order_by("-date_posted")

    context = {
        "post":post,
        "comments":comments
    }
    return render(request,'blog/detail.html',context)

def reviewview(request):
    return render(request,"blog/review.html")

blog/templates/blog/all.html
{% extends "blog/base.html" %}
{%load static%}
{% block content%}
<!-- Page Header -->
<header class="masthead" style="height:100px;background-image: url('https://images.unsplash.com/photo-1512756290469-ec264b7fbf87?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=649&q=80')">
<div class="overlay"></div>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
<!--       <div class="site-heading">
        <img style="height: 120px; width: 120px;" src="{% static 'blog/img/120px.png'%}">
        <h1>Tech Rant</h1>    
        <span class="subheading">Screaming about technology daily</span>
      </div>
 -->    </div>
  </div>
</div>
</header>

 <!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
    	{% for post in posts%}
      <div class="post-preview">
        <a href="{% url 'blog:post_detail' post.id%}">
          <h4 class="post-title">
            {{post.title}}
          </h4>
          <p class="small post-subtitle">
            {{post.subtitle}}
          </p>
        </a>
        <p class="small post-meta">Posted by
          <a href="#">{{post.author.username}}</a>
          on {{ post.date_posted|date:"F d, Y" }}</p>
      </div>
      <hr>
      {%endfor%}
    </div>
  </div>
</div>

  <hr>
{% endblock%}

blog/templates/blog/base.html
{%load static %}
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <link rel="icon" href = "{%static 'blog/img//40px.png'%}" sizes="16x16" type="image/png">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

    {% if title %}
        <title>Tech Rant - {{ title }}</title>
    {% else %}
        <title>Tech Rant</title>
    {% endif %}
  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
<!--   <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'> -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Aladin&family=Fondamento&display=swap" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{%static 'blog/css/clean-blog.css'%}" rel="stylesheet">
  <!--  -->
  <style type="text/css">
  	*{
  	box-sizing: border-box;
  	font-family: 'Quicksand', sans-serif;	
  	}
  </style>
  <script async src="https://cse.google.com/cse.js?cx=54c358f2ed8d23de9"></script>
</head>
<body>
  <!-- Navigation -->
{%if user.is_authenticated%}
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:blog_home'%}"><img style="height: 40px; width: 40px;" src="{% static 'blog/img/40px.png'%}"> Tech Rant</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:blog_home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:aboutme'%}">About Me</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'logout'%}">Log out</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'profile'%}">Profile</a>
          </li>
          <li class="nav-item">
              <button class="btn btn-primary" type="submit" data-toggle="modal" data-target="#myModal"><i class="fa fa-search"></i></button>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<!-- Search Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Search Tech Rant</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <!-- Place this tag where you want the search box to render. -->
        <div class="gcse-searchbox"></div>

        <hr/>

        <!-- Place this tag where you want the search results to render. -->
        <div class="gcse-searchresults"></div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>
{%else%}
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:blog_home'%}"><img style="height: 40px; width: 40px;" src="{% static 'blog/img/40px.png'%}"> Tech Rant</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:blog_home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:aboutme'%}">About Me</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'login'%}">Sign In</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'register'%}">Sign Up</a>
          </li>
<!--           <li class="nav-item">
           <form class="form-inline" action="" method="POST">
            {% csrf_token %}
              <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search posts...">
              <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
            </form>
          </li> -->
        </ul>
      </div>
    </div>
  </nav>
{% endif %}
{% block content%}
{% endblock %}
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://twitter.com/Eli_okello">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://github.com/Elijah-web">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="{% url 'blog:create'%}">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fas fa-plus fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="small text-center text-muted">Hit the &plus; icon to start writing with Tech Rant</p>
          <hr>
          <p class="copyright text-muted">Copyright &copy; Tech Rant <span id="demo"></span></p>
          <script type="text/javascript">
              var d = new Date();
              document.getElementById("demo").innerHTML = d.getFullYear();
          </script>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{%static 'blog/vendor/jquery/jquery.min.js'%}"></script>
  <script src="{%static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Custom scripts for this template -->
  <script src="{%static 'blog/js/clean-blog.min.js'%}"></script>

</body>
</html>

blog/templates/blog/create.html
{% extends 'blog/base.html'%}
{% load static %}
{% block content%}
<!-- Page Header -->
<header class="masthead" style="height:100px;background-image: url('https://images.unsplash.com/photo-1512756290469-ec264b7fbf87?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=649&q=80)">
<div class="overlay"></div>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
<!--       <div class="site-heading">
        <img style="height: 120px; width: 120px;" src="{% static 'blog/img/120px.png'%}">
        <h1>Tech Rant</h1>    
        <span class="subheading">Screaming about technology daily</span>
      </div>
 -->    </div>
  </div>
</div>
</header>
<div class="container" id="contact_form">
	<h2>Add Blog Post</h2>
  <p class="text-secondary text-center small">After you save your super awesome blog post, it will be reviewed by the team at Tech Rant and it will be published if it meets our standards. Thank you for writing with Tech Rant</p>
  <form name="contact" action="{% url 'blog:create'%}" method="post" enctype="multipart/form-data">
  	{% csrf_token %}
    <fieldset>
      <div class="form-group">
      <label for="name">Title</label>
      <input type="text" name="title" id="name" minlength="3" placeholder="Enter title" class="form-control" required/>
      </div>
       
      <div class="form-group">
      <label for="email" id="email_label">Subtitle</label>
      <input required type="text" name="subtitle" id="email" placeholder="Enter Subtitle" class="form-control"/>
      </div>
      
      <div class="form-group">
      <label for="image" id="phone_label">Post Header Image</label>
      <input required type="text" name="image" id="img" placeholder="Enter the link to your image" class="form-control"/>
      </div>

      <div class="form-group">
      <label for="phone" id="phone_label">Content</label>
	      <div id="editorjs"></div>
      <input hidden type="text" name="content" id="y" class="form-control" placeholder="Enter the content below &darr; Hit the &plus; for more editing options"/>
      </div>
		<div id="draft"></div>
		<button type="submit" onclick="myFunction();" class="btn btn-primary">Save Post</button>
    </fieldset>
  </form>
</div>
<script src="{% static 'blog/create/editor.js'%}"></script>
<script src="{% static 'blog/create/header.js'%}"></script>
<script src="{% static 'blog/create/paragraph.js'%}"></script>
<script src="{% static 'blog/create/simpleImage.js'%}"></script>
<script src="{% static 'blog/create/embed.js'%}"></script>
<script src="{% static 'blog/create/delimeter.js'%}"></script>
<script src="{% static 'blog/create/raw.js'%}"></script>
<script src="{% static 'blog/create/edjsParser.js'%}"></script>
<script type="text/javascript">

const editor = new EditorJS({
    holder: 'editorjs',
/** 
     * Available Tools list. 
     * Pass Tool's class or Settings object for each Tool you want to use 
     */
   tools:{
      raw:RawTool,
       header:Header,
       delimiter: Delimiter,
       paragraph: {
        class: Paragraph,
        inlineToolbar: true,
      },
      embed: Embed,
      image: SimpleImage,
   }
}
);

function myFunction(){
  editor.save().then((output)=>{
    console.log('Data: ',output);
    var json_me = JSON.stringify(output);
    // document.getElementById("data").innerHTML = json_me;
    // send the string to the server\0
    var content = document.getElementById("y");
    content.value = json_me;
    // document.getElementById("data").innerHTML = content.value;
    return true
  }).catch((error)=>{
  console.log('Saving failed:',error)
  });
}
</script>
{% endblock %}

blog/templates/blog/detail.html
{%extends "blog/base.html"%}
{% load static %}
{% block content %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{post.image}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1 >{{post.title}}</h1>
            <p class="small">{{post.subtitle}}</p>
            <p class="small">Posted by
              <a class="text-white" href="#">{{post.author.username}}</a>
              on {{ post.date_posted|date:"F d, Y" }}</p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          {% if post.publish %}<p hidden></p>{%else%}<p class="small text-danger">This post is not officially published by <a href="{% url 'blog:blog_home'%}">Tech Rant</a>. It is just a draft.</p>{% endif %}
          <div id="thecontent">
            <p hidden id="json">{{post.content}}</p>
          </div>
          <hr>
          <div class="container">
            <h3 id="commentstart">Comments</h3>
            <p id="demo1"></p>
            <form method="post" class="example" action="{%url 'blog:comment' post.id%}">
              {% csrf_token %}
              <input id="comment-input" onfocus="check();" type="text" placeholder="Add Comment" name="comment">
              <button id="frm-btn" type="submit"><i class="fas fa-paper-plane"></i></button>
            </form>
            {% for comment in comments%}
              <div class="container20">
                <span style="font-size: 13px;" class="text-primary"><strong>{{comment.author.username}}</strong></span>
                <span style="font-size: 13px;"> {{comment.date_posted}}</span><hr>
                <p class="small">{{comment.content}}</p>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </article>
  <hr>
  <script type="text/javascript">
    function check(){
      var is_authenticated = {%if user.is_authenticated%}1{% else %}0{%endif%};
      var msg = document.getElementById("demo1");
      if(is_authenticated)
      {
        msg.className = "small text-center text-success";
        msg.innerHTML = "You're logged in! <li class=\"fa fa-check-circle\"></li>";
      }
      else
      {
        msg.className = "small text-center text-danger";
        msg.innerHTML = "Please login to be able to comment! <li class=\"fas fa-frown\"></li> <a href=\"{%url 'login' %}?next=/detail/{{post.id}}#commentstart\">Log In</a>";
        document.getElementById("comment-input").disabled = true;
        document.getElementById("frm-btn").disabled = true;
      }
    }
  </script>
<script src="{% static 'blog/create/edjsParser.js'%}"></script>
<script type="text/javascript">
const customParsers = {
  raw: function(data, config){
    var raw_markup = "<textarea class=\"code_textbox\" disabled>"+data.html;
    return raw_markup;
  },
}
var json_me = document.getElementById("json").innerHTML;
var obj = JSON.parse(json_me);
const parser = new edjsParser(undefined,customParsers);
const markup = parser.parse(obj);
document.getElementById('thecontent').innerHTML = markup;
</script>
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{%load static%}
{% block content%}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1542&q=80')">
    <div class="overlay"></div>
    <div class="container-fluid">
      <div style="background-color: rgba(white, 0.7);" class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Tech Rant</h1>    
            <p class="post-subtitle small text-center"> All of the biggest technological inventions created by man - the airplane, the automobile, the computer - says little about his intelligence, but speaks volumes about his laziness. - Mark Kennedy (Author)</p>
            <a href="{%url 'blog:create'%}"><button class="btn btn-primary">Start Writing <li class="fas fa-plus"></li></button></a>
          </div>
        </div>
      </div>
    </div>
  </header>

 <!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
    	{% for post in posts%}
      <div class="post-preview">
        <a href="{% url 'blog:post_detail' post.id%}">
          <h4 class="post-title">
            {{post.title}}
          </h4>
          <p class="small post-subtitle">
            {{post.subtitle}}
          </p>
        </a>
        <p class="small post-meta">Posted by
          <a href="#">{{post.author.username}}</a>
          on {{ post.date_posted|date:"F d, Y" }}</p>
      </div>
      <hr>
      {%endfor%}
      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="{% url 'blog:all'%}">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>

  <hr>
{% endblock%}

blog/templates/blog/review.html
{% extends "blog/base.html" %}
{% block content %}
{% load static%}
  <header class="masthead" style="height:100px; background-image: url('https://images.unsplash.com/photo-1512756290469-ec264b7fbf87?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=649&q=80')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <!-- <img style="height: 120px; width: 120px;" src="{% static 'blog/img/120px.png'%}"> -->
            <!-- <h1>Tech Rant</h1>     -->
            <!-- <span class="subheading">Screaming about technology daily</span> -->
          </div>
        </div>
      </div>
    </div>
  </header>

   <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
      	<h2 class="text-info">This blog post is being reviewed please wait for the team at Tech Rant to review the article after which it will be published.</h2>
    </div>
      </div>
    </div>
  </div>
{% endblock content %}